### PR TITLE
Add ubuntu 24.04 to `build_test.yml`

### PR DESCRIPTION
**Pull request by bennibbelink**
Adds ubuntu 24.04 to CI.

### CODE REVIEW

**Comment by bennibbelink** [comment]
Seeing the same failure here as in https://github.com/cyclus/cyclus/pull/1816 on `24.04_apt`.  Cyclus is installed with the latest numpy from `apt` (`numpy==1.26.4`), but cymetric is installed with numpy from `pip` (`numpy==2.12`) which has a different API.  This isn't an issue on our other `apt` builds because they have older versions of python that do not support `numpy>==2`.  

Few ways I can think to resolve this:
- pin numpy; this doesn't have a clear end in sight until either pytables v3.10 is available via apt or we stop supporting ubuntu 24.04
- add the `--no-deps` flag to the `pip install` command.  This way pip will not install dependencies and cymetric will just use the version of numpy alread installed on the system.  The only issue with this is that `matplotlib` is not a dependency for cyclus or cymetric, so it does not exist on the system.  It doesn't affect tests, but a user might need it (this is easily fixed by installing matplotlib in the cymetric dockerfile)
- template `pyproject.toml` so that we can generate it on the fly to pin package versions to those that exist on the system already. This should be fairly straightforward, just requires some modifications to the setup script (and is less transparent to a user trying to install cymetric on their own)

**Comment by gonuke** [comment]
My gut tells me that Canonical will need to address this for the 24.04 version at some point, as the upgrade to numpy 2.0 will be hitting a lot of people.  It seems like numpy 2.x is also not available via apt for 24.04 which may limit pytables being updated too?

I think if we pin numpy for Cymetric to match what we have for Cyclus, that is probably the most consistent (and me in 18 months will be trying to remember why we did this)

**Comment by bennibbelink** [comment]
I implemented the second bullet above.  If we want to explicitly pin numpy, then we will likely need to modify the setup script to generate `pyproject.toml` dynamically.  As it is now, it is (implicitly?) pinned to the existing version due to the fact that pip does not install any dependencies.

**Review by gonuke — APPROVED** [review]
Thanks @bennibbelink

**Pull request merged**
