### PR TITLE
Bytes Fixes

### PR DESCRIPTION
**Pull request by scopatz**
This solves a number of bytes fixes that are associated with Python 3 and probably were the root cause of the recent segfaults.  I would say that this is pretty critical for you to try out @opotowsky

### CODE REVIEW

**Comment by opotowsky** [comment]
@scopatz, can you ascertain if these testing failures are because my laptop doesn't play well with Cyclus or not?

..F.....E.E.
======================================================================
ERROR: test_evaluator.test_eval(<cymetric.cyclus.Hdf5Back object at 0xb22ce68c>, 'test.h5', <class 'cymetric.cyclus.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/opotowsky/cyclus/cymetric/tests/test_evaluator.py", line 15, in test_eval
    df = evaluator.eval('Materials', db)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/evaluator.py", line 82, in eval
    return e.eval(str(metric), conds=conds)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/evaluator.py", line 59, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/evaluator.py", line 62, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/root_metrics.py", line 27, in __call__
    return self.db.query(self.name, conds=conds)
  File "cyclus.pyx", line 123, in cymetric.cyclus._FullBackend.query (/home/opotowsky/cyclus/cymetric/build/cymetric/cyclus.cxx:2586)
RuntimeError: table 'Resources' does not exist in 'test.h5'.

======================================================================
ERROR: test_root_metrics.test_resources(<cymetric.cyclus.Hdf5Back object at 0xb22e4aec>, 'test.h5', <class 'cymetric.cyclus.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/opotowsky/cyclus/cymetric/tests/test_root_metrics.py", line 18, in test_resources
    obs = r()
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/root_metrics.py", line 27, in __call__
    return self.db.query(self.name, conds=conds)
  File "cyclus.pyx", line 123, in cymetric.cyclus._FullBackend.query (/home/opotowsky/cyclus/cymetric/build/cymetric/cyclus.cxx:2586)
RuntimeError: table 'Resources' does not exist in 'test.h5'.

======================================================================
FAIL: test_cyclus.test_conds_comp(<cymetric.cyclus.Hdf5Back object at 0xb2335aec>, 'test.h5', <class 'cymetric.cyclus.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/opotowsky/cyclus/cymetric/tests/test_cyclus.py", line 40, in test_conds_comp
    assert_less(0, len(df))
AssertionError: 0 not less than 0

----------------------------------------------------------------------
Ran 12 tests in 0.806s

FAILED (errors=2, failures=1)

**Comment by scopatz** [comment]
These are all HDF5 issues, so if you are still having HDF5 woes then yes. Go into cymetric/tests then report back what `cymetric test.h5 -l` says.

**Comment by opotowsky** [comment]
I am, so, as expected:

opotowsky@opotowsky ~/cyclus/cymetric/tests (master) $ cymetric test.h5  -l
AgentEntry
AgentStateAgent
AgentState_agents_NullRegionInfo
AgentState_cycamore_BatchReactorCommodPrefs
AgentState_cycamore_BatchReactorCommodityRecipeContext_inoutmap
AgentState_cycamore_BatchReactorInfo
AgentState_cycamore_BatchReactorInitialInv
AgentState_cycamore_BatchReactorPrefChanges
AgentState_cycamore_DeployInstBuildOrder
AgentState_cycamore_SourceInfo
BlobKeys
BlobVals
BuildSchedule
Compositions
DecayMode
Info
InputFiles
NextIds
Prototypes
Recipes
Snapshots
StringKeys
StringVals
XMLPPInfo

**Comment by opotowsky** [comment]
I'd say it's safe to merge and I need a new laptop :-)

**Comment by scopatz** [comment]
Weird. Yeah. Your HDF5 is seriously messed up :)

**Comment by opotowsky** [comment]
Thanks so much for the quick fix @scopatz!

**Comment by scopatz** [comment]
np, ace.

**Pull request merged**
