### PR TITLE
Fixnames

### PR DESCRIPTION
**Pull request by opotowsky**
Since no abbreviations are currently accepted, I have updated metrics names to be fully spelled out, aside from U (Uranium Mined) and FCO (for fco/bright-light-specific metrics). Feel free to make suggestions for these two I excluded updating.

### CODE REVIEW

**Comment by deniadjokic** [comment]
Great! I would opt for full caps for FCO in the metric names. (i.e. FCOElectricityGenerated)

**Comment by opotowsky** [comment]
@deniadjokic, I'll let @scopatz weigh in because I think he reasoned `Fco` over `FCO` for style reasons. I'm not sure how to handle the "no abbreviation" rule with FCO and SWU!

**Comment by deniadjokic** [comment]
Anthony says he doesn't care and thinks they're both equivalent. I think
FCO and SWU are acronyms can stay because they're (relatively) widely
accepted.

---
Denia Djokic
Postdoctoral Researcher
UC Berkeley Nuclear Engineering

**Comment by opotowsky** [comment]
Noted on the acronyms for now, I'll keep em!

I initially liked FCO over Fco, but when there's always a capital letter after the acronym you get:
`FCOUMined` versus `FcoUMined` or `FCOSWU` versus `FcoSWU`. What do you think?

**Comment by deniadjokic** [comment]
I see what you mean... I personally don't have a problem with too many capital letters, but perhaps just because I've been staring at them for so long that my brain automatically knows how to separate them. :) Underscores seem like an inelegant solution... unless maybe you use FCO as a suffix? Or spell out the word "Uranium"? I would keep SWU as is, though, since it's such a standard acronym.

**Comment by opotowsky** [comment]
I initially hesitated to spell out uranium but since we are trying to be as anti-abbreviation as possible but I'll definitely spell it out. And I think @scopatz had a reason for using FCO as a prefix instead of a suffix (the best reason I can come up with is so they are all next to each other in the online documentation). Basically now the only issue is `FCOSWU`.

I checked the style guide and for python it should be `ClassName` and `function_name`. These metrics are technically classes so having something all caps is probably at odds with the style guide. I'm definitely for keeping SWU as an acronym. How about `FcoSwu` for consistency?

**Comment by opotowsky** [comment]
(and then we will have to document somewhere that FCO and SWU are acceptable acronyms for metrics - making an issue now)

**Comment by deniadjokic** [comment]
Did some research too. This is what the internet says on this type of issue: http://stackoverflow.com/questions/2853531/how-do-you-pep-8-name-a-class-whose-name-is-an-acronym, or http://stackoverflow.com/questions/22133540/python-naming-with-acronyms. Hmmm.

**Comment by opotowsky** [comment]
Well it looks like we can be technically right (`FCOSWU`) or functionally right (`FcoSwu`) but not both! You leaning one way or the other after looking at those @deniadjokic? I'm leaning functional. But can be swayed with a delicate swoosh of air in the other direction if you so lean the other way :-)

**Comment by mbmcgarry** [comment]
I lean toward functionally right, if you’re still looking for input.

On May 5, 2015, at 10:40 PM, opotowsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Well it looks like we can be technically right (FCOSWU) or functionally right (FcoSwu) but not both! You leaning one way or the other after looking at those @deniadjokic<https://github.com/deniadjokic>? I'm leaning functional. But can be swayed with a delicate swoosh of air in the other direction if you so lean the other way :-)

—
Reply to this email directly or view it on GitHub<https://github.com/cyclus/cymetric/pull/61#issuecomment-99312211>.

*************************************************************************
Meghan McGarry, PhD ~ http://mbmcgarry.github.io/
Postdoctoral Fellow, Consortium for Verification Technology
Computational Nuclear Engineering ~ http://cnerg.engr.wisc.edu
Engineering Physics ~ UW-Madison ~ 608-263-6974
*************************************************************************

**Comment by opotowsky** [comment]
Thanks @mbmcgarry! I'll update it that way for now  

closing to move PR to develop branch

**Comment by deniadjokic** [comment]
Guess I missed the train, but after all this discussion, I was delicately swooshing in the direction of functionally right too. Hooray!

**Comment by opotowsky** [comment]
S'all good, that fix wasn't even in this PR anyway (since the now `FcoSwu` is plaguing me with a test failure)

**Pull request closed without merging**
