### PR TITLE
Adding explicit inventory root metrics and metrics

### PR DESCRIPTION
**Pull request by opotowsky**
Note the data type for explicit inventory compact does not allow for pandas manipulation so there is only the root metric added

### CODE REVIEW

**Comment by rwcarlsen** [comment]
This looks generally good.  The only main thing I am wondering is what primary metrics we want to provide for inventories.  Arrielle has put 2 special metrics in:

* inventories per agent per buffer name per time step per nuclide
* inventories per buffer name per time step per nuclide

There are all sorts of other combinations such as:

* per buffer name per time step
* per agent per time step per nuclide
* per time step per nuclide
* etc.

I just want to make sure that we are being deliberate for what we are including and for what we are leaving out - rather than it just being what came to mind first.  Thoughts @scopatz @gonuke @mbmcgarry @Baaaaam ?

**Comment by mbmcgarry** [comment]
Unclear to me - How are these two options different conceptually?  Why would a buffer name not already be per-agent?

-Meghan


On May 2, 2016, at 10:22 AM, Robert Carlsen <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks generally good. The only main thing I am wondering is what primary metrics we want to provide for inventories. Arrielle has put 2 special metrics in:

  *   inventories per agent per buffer name per time step per nuclide
  *   inventories per buffer name per time step per nuclide

There are all sorts of other combinations such as:

  *   per buffer name per time step
  *   per agent per time step per nuclide
  *   per time step per nuclide
  *   etc.

I just want to make sure that we are being deliberate for what we are including and for what we are leaving out - rather than it just being what came to mind first. Thoughts @scopatz<https://github.com/scopatz> @gonuke<https://github.com/gonuke> @mbmcgarry<https://github.com/mbmcgarry> @Baaaaam<https://github.com/Baaaaam> ?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/cyclus/cymetric/pull/100#issuecomment-216265866>

*************************************************************************
Meghan McGarry, PhD ~ http://mbmcgarry.github.io/
Scientist, Consortium for Verification Technology
Computational Nuclear Engineering ~ http://cnerg.engr.wisc.edu
Engineering Physics ~ UW-Madison ~ 608-263-6974
*************************************************************************

**Comment by rwcarlsen** [comment]
Multiple buffers per agent.

**Comment by opotowsky** [comment]
I did exactly what @rwcarlsen said, the first thing that came to mind. My reasoning was to provide some examples with the inventory tables. But I agree; I think if there is no obvious very common use-case then maybe we should not include random inventory metrics in cymetric.

**Comment by rwcarlsen** [comment]
@opotowsky - sorry if it seemed like I was picking on you - I was just soliciting a few thoughts.  I'll merge by the end of the day unless anybody has other thoughts/suggestions for consideration.

**Comment by opotowsky** [comment]
@rwcarlsen you'll know when I think you're picking on me!!!

**Pull request merged**
