### PR TITLE
Pure Python Package

### PR DESCRIPTION
**Pull request by scopatz**
Now that the hard bits have been moved into cyclus proper.  Almost 3k LOC deletions :)

@FlanFlanagan and @Baaaaam, would you mind taking a look please?

### CODE REVIEW

**Comment by scopatz** [comment]
The failure seems to be from not grabbing the latest cyclus container.  This does seem to work locally.

**Comment by Baaaaam** [comment]
I am testing it:
(I now have a branch named `scopatz-pure` on my computer. :) )

**Comment by Baaaaam** [comment]
I have tried it:

installation is way more quiet than it used to be:

> python setup.py install --user                                                                                                                    scopatz-pure
> running install
> running build
> running build_py
> creating build
> creating build/lib
> creating build/lib/cymetric
> copying cymetric/__init__.py -> build/lib/cymetric
> copying cymetric/brightlite_root_metrics.py -> build/lib/cymetric
> copying cymetric/cycamore_root_metrics.py -> build/lib/cymetric
> copying cymetric/evaluator.py -> build/lib/cymetric
> copying cymetric/execution.py -> build/lib/cymetric
> copying cymetric/fco_metrics.py -> build/lib/cymetric
> copying cymetric/main.py -> build/lib/cymetric
> copying cymetric/metrics.py -> build/lib/cymetric
> copying cymetric/root_metrics.py -> build/lib/cymetric
> copying cymetric/schemas.py -> build/lib/cymetric
> copying cymetric/tools.py -> build/lib/cymetric
> running build_scripts
> creating build/scripts-3.5
> copying and adjusting scripts/cymetric -> build/scripts-3.5
> changing mode of build/scripts-3.5/cymetric from 644 to 755
> running install_lib
> running install_scripts
> copying build/scripts-3.5/cymetric -> /Users/mouginot/Library/Python/3.5/bin
> changing mode of /Users/mouginot/Library/Python/3.5/bin/cymetric to 755
> running install_egg_info
> Removing /Users/mouginot/Library/Python/3.5/lib/python/site-packages/cymetric-1.4.0-py3.5.egg-info
> Writing /Users/mouginot/Library/Python/3.5/lib/python/site-packages/cymetric-1.4.0-py3.5.egg-info


nostest are failing, but I never had them work on mac....

but when trying some script I have it fails to import Cymetric:


> import numpy as num
> import cymetric as cym
> import pandas as pd

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-a5ce046e680c> in <module>()
>       1 import numpy as num
> ----> 2 import cymetric as cym
>       3 import pandas as pd
> 
> /Users/mouginot/Library/Python/3.5/lib/python/site-packages/cymetric/__init__.py in <module>()
>       2 from __future__ import unicode_literals, print_function
>       3 
> ----> 4 from cyclus.typesystem import *  # only grabs code generated definitions
>       5 from cyclus.lib import Datum, FullBackend, SqliteBack, Hdf5Back, \
>       6         Recorder
> 
> ImportError: No module named 'cyclus'


I might have done something wrong.... (I build Cymetric against cyclus/develop)

**Comment by Baaaaam** [comment]
I tried on my macbook and on ubuntu 16.04:
macbook:
- installation ok
- nosetest not working:

> Failure: ImportError (No module named 'cyclus') ... ERROR
> Failure: ImportError (No module named 'cyclus') ... ERROR
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.data is not yet QA compliant.
>   return f(*args, **kwds)
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.material is not yet QA compliant.
>   return f(*args, **kwds)
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.enrichment is not yet QA compliant.
>   return f(*args, **kwds)
> Failure: ImportError (No module named 'cyclus') ... ERROR
> Failure: ImportError (No module named 'cyclus') ... ERROR
> Failure: ImportError (No module named 'cyclus') ... ERROR
> 
> ======================================================================
>
> ERROR: Failure: ImportError (No module named 'cyclus')
>
> ---------------------------------------------------------------------- 

As nosiest where not working before on MacOS I tried to run a script of mine which use cymetric but fails also to find 'cyclus'

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-2-a5ce046e680c> in <module>()
>       1 import numpy as num
> ----> 2 import cymetric as cym
>       3 import pandas as pd
> 
> /Users/mouginot/Library/Python/3.5/lib/python/site-packages/cymetric/__init__.py in <module>()
>       2 from __future__ import unicode_literals, print_function
>       3 
> ----> 4 from cyclus.typesystem import *  # only grabs code generated definitions
>       5 from cyclus.lib import Datum, FullBackend, SqliteBack, Hdf5Back, \
>       6         Recorder
> 
> ImportError: No module named 'cyclus'


on ubuntu 16.04:
- installation seems ok
- nosetest : seg fault on the second one
- loading cymetric in python:
> Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
> [GCC 5.3.1 20160413] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cymetric as cym
> *** Error in `python': munmap_chunk(): invalid pointer: 0x00000000029fc3e0 ***
> ======= Backtrace: =========

[here](https://gist.github.com/Baaaaam/51dea1d68b3f1d717b840513bd139792) is the complete backtrace

**Comment by scopatz** [comment]
Thanks for trying this out @Baaaaam. Did you install cyclus with the python bindings?  It seems like that is the piece that you are missing.

**Comment by Baaaaam** [comment]
@scopatz do I need to do anything special to have the python bindings ?

**Comment by scopatz** [comment]
You need to have Python, cython, jinja2, and numpy installed to build it

**Comment by scopatz** [comment]
If you don't have Cython, it will skip.  If you do have cython but not the others it will fail.  The output of cmake should tell you.

**Comment by Baaaaam** [comment]
I have all of them I think

> /opt/local/bin/cmake
> -- The C compiler identification is AppleClang 7.0.0.7000176
> -- The CXX compiler identification is AppleClang 7.0.0.7000176
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> 
> -- Dependency Root Dir (DEPS_ROOT_DIR):
> -- Dependency Hints (DEPS_HINTS):
> -- Dependency Binary Hints (DEPS_BIN_HINTS):
> -- Dependency Library Hints (DEPS_LIB_HINTS):
> -- Dependency Include Hints (DEPS_INCLUDE_HINTS):
> -- Not Found Tcmalloc: Tcmalloc_LIBRARY-NOTFOUND
> -- Found LibXml2: /opt/local/lib/libxml2.dylib (found version "2.9.4")
> -- LibXML++ find package args: LibXml2;REQUIRED
> -- LibXML++ find package args: Glibmm;REQUIRED
> -- Glibmm find package args: Glib;REQUIRED
> -- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1")
> -- Checking for module 'glib-2.0'
> --   Found glib-2.0, version 2.50.1
> -- Found glib-2.0: /opt/local/include/glib-2.0, /opt/local/lib/libglib-2.0.dylib
> -- Glibmm find package args: SigC++;REQUIRED
> -- Checking for module 'sigc++-2.0'
> --   Found sigc++-2.0, version 2.4.1
> -- Found SigC++
> -- Checking for module 'glibmm-2.4'
> --   Found glibmm-2.4, version 2.44.0
> -- Found Glibmm
> -- Checking for module 'libxml++-2.6'
> --   Found libxml++-2.6, version 2.38.1
> -- Found LibXML++
> -- Found Sqlite3 header file in /opt/local/include
> -- Found Sqlite3 libraries: /opt/local/lib/libsqlite3.dylib
> -- Found HDF5: /opt/local/lib/libhdf5_hl.dylib;/opt/local/lib/libhdf5.dylib;/opt/local/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib
> --    HDF5 Root:
> --    HDF5 Include directory: /opt/local/include
> --    HDF5 Library directories: /opt/local/lib
> --    HDF5 Libraries: /opt/local/lib/libhdf5_hl.dylib;/opt/local/lib/libhdf5.dylib;/opt/local/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib
> -- Boost version: 1.59.0
> -- Found the following Boost libraries:
> --   program_options
> --   filesystem
> --   system
> --   serialization
> --    Boost Root:
> --    Boost Include directory: /opt/local/include
> --    Boost Library directories: /opt/local/lib
> --    Boost Program Options location: /opt/local/lib/libboost_program_options-mt.dylib
> --    Boost System location: /opt/local/lib/libboost_system-mt.dylib
> --    Boost Filesystem location: /opt/local/lib/libboost_filesystem-mt.dylib
> --    Boost Serialization location: /opt/local/lib/libboost_serialization-mt.dylib
> -- Looking for dgemm_
> -- Looking for dgemm_ - found
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - found
> -- Found Threads: TRUE
> -- A library with BLAS API found.
> -- Looking for cheev_
> -- Looking for cheev_ - found
> -- A library with LAPACK API found.
> 	Found LAPACK Libraries: /System/Library/Frameworks/Accelerate.framework;/System/Library/Frameworks/Accelerate.framework
> 	COIN Root Dir:
> -- COIN_ROOT_DIR hint is :
> -- Coin multiple library dependency status:
> 	COIN Include Dir: /opt/local/include/coin
> 	COIN CBC: /opt/local/lib/libCbc.dylib
> 	COIN CBC solver: /opt/local/lib/libCbcSolver.dylib
> 	COIN CGL: /opt/local/lib/libCgl.dylib
> 	COIN CLP SOLVER: /opt/local/lib/libClpSolver.dylib
> 	COIN CLP: /opt/local/lib/libClp.dylib
> 	COIN UTILS: /opt/local/lib/libCoinUtils.dylib
> 	COIN OSI: /opt/local/lib/libOsi.dylib
> 	COIN OSI CBC: /opt/local/lib/libOsiCbc.dylib
> 	COIN OSI CLP: /opt/local/lib/libOsiClp.dylib
> 	COIN ZLIB: /opt/local/lib/libz.dylib
> 	COIN BZ2: /opt/local/lib/libbz2.dylib
> -- Found COIN: /opt/local/include/coin
> -- Found COIN Include Dirs: /opt/local/include/coin
> -- Found PCRE Libraries (optional): /opt/local/lib/libpcre.dylib
> -- Found OPENBLAS Libraries (optional): OPENBLAS_LIBRARIES-NOTFOUND
> -- Found CLPSOLVER Libraries (optional): /opt/local/lib/libClpSolver.dylib
> -- Found ICONV Libraries (optional): /opt/local/lib/libiconv.dylib
> -- Found ICUDATA Libraries (optional): /opt/local/lib/libicudata.dylib
> -- Found ICUI18N Libraries (optional): /opt/local/lib/libicui18n.dylib
> -- Found ICUUC Libraries (optional): /opt/local/lib/libicuuc.dylib
> -- Found PythonInterp: /opt/local/bin/python (found version "3.5.2")
> -- Found PythonLibs: /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m.dylib (found version "3.5.2")
> -- PYTHON_EXECUTABLE: /opt/local/bin/python
> -- Found Cython: /opt/local/bin/cython
> -- Found Cython: TRUE
> -- Cython Version: Cython version 0.25.1
> -- NUMPY_VERSION_STRING = 1.11.2
> -- Found Numpy: 1.11.2
> -- Found Jinja2: TRUE
> -- core version ($CYCLUS_CORE_VERSION) set to: 1.4.1-64-ge4b34f1
> -- Found '/Users/mouginot/work/app/cyclus/cyclus/share/cyclus_nuc_data.h5'
> -- Starting construction of build files for agent: test_agent

**Comment by scopatz** [comment]
Ahh Ok, so it found Python v3.5, so you have to use that version of Python when testing. At the end of the build, it should say where it installed the python package to.  My guess is `/opt/local/lib/python/site-packages`.  Is that on your $PYTHONPATH?

**Comment by scopatz** [comment]
Or whatever your install prefix is....

**Comment by Baaaaam** [comment]
ok I have some problem with nosiest on my mac, but my script are working smoothly.

will try it on my ubuntu computer...

**Comment by Baaaaam** [comment]
on ubuntu:

> Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
> [GCC 5.3.1 20160413] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cymetric as cym
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/mouginot/.local/lib/python2.7/site-packages/cymetric/__init__.py", line 4, in <module>
>     from cyclus.typesystem import *  # only grabs code generated definitions
> ImportError: No module named type system

I am again doing something wrong ?

**Comment by scopatz** [comment]
Did you install cyclus into Python 2.7 or 3.5?

**Comment by Baaaaam** [comment]
on my mac 3.5

on ubuntu computer 2.7

**Comment by scopatz** [comment]
Is the cyclus dir in the correct site-packages dir?

**Comment by scopatz** [comment]
Maybe we can set up a time to look at this next week via Hangouts?

**Comment by Baaaaam** [comment]
next week I am at the Winter ANS meeting. Not sure if I will have the time.

If you think it is a configuration issue, I try to figure it out myself, if I can't I go back to you !

**Comment by scopatz** [comment]
Yeah, I think the python you are using when you run is not the smae one cyclus installs to.

**Comment by FlanFlanagan** [comment]
Hey guys, I think part of the issue here is the cyclus build on circleci isn't up to date with develop.

**Comment by Baaaaam** [comment]
maybe but on ci Cymetric should be builded using Cymetric-deps container which should have been updated on the attempt of release last week...

it is nevertheless possible that the Cymetric-deps was updated to early (before the updated cycamore container was pushed on docker hub...)

**Comment by Baaaaam** [comment]
I'll try to force update Cymetric-deps container... to see if it works

**Comment by scopatz** [comment]
I think it is the cyclus-latest image that is out of date (and needs the develop version), not the cymetric-deps. But I could be wrong.

**Comment by FlanFlanagan** [comment]
https://gist.github.com/FlanFlanagan/111146f7cae01d1a49af5bf9cc22498d

From my current issue

**Comment by Baaaaam** [comment]
the cymetric docker is build against the cymetric-dps which is build against the cycamore:latest

the cycamore:latest is updated at each merged PR on develop

**Comment by Baaaaam** [comment]
ok I got it.

Cymetric-deps depends on cycamore, which has not been updated since you pure-python merge on cyclus!

**Comment by Baaaaam** [comment]
@scopatz @FlanFlanagan could one of you merge: https://github.com/cyclus/cycamore/pull/439

to force the update of the cycamore docker ?

**Comment by Baaaaam** [comment]
seems like cycamore:develop is broken too :(

**Comment by scopatz** [comment]
Good catch @Baaaaam !

**Comment by Baaaaam** [comment]
I re-do the force push Cymetric-deps container

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Hi @Baaaaam, did the last deps build really build off of the develop version of cyclus?

**Comment by Baaaaam** [comment]
yes with the modification I made this summer, cycamore:latest is built against cyclus:latest which is updated on develop merge

**Comment by scopatz** [comment]
Were the python bindings built on the latest cyclus?

**Comment by Baaaaam** [comment]
it supposes to be as we merge the python built PR on cyclus develop...

**Comment by scopatz** [comment]
hmm Ok.

**Comment by Baaaaam** [comment]
python built merged 9 days ago
cyclus:latest: last update 2 days ago (`WIP: HDF5 'Create' Code Generation` PR merged 2 days ago)
cycamore:latest: last update 21 minutes ago

**Comment by Baaaaam** [comment]
I think I find the issue source:

As I manually update the cymetric-deps, docker uses the local version of cycamore:latest that is on my computer... which was 10 weeks old.


so the cymetric-deps I built and update was on a old version of cycamore:latest.


I am pulling the proper version of cycamore:latest, so it should fix that! (this is slow 1Go to download from the hotel connection....)

**Comment by scopatz** [comment]
Ahh! Thanks for tracking this down @Baaaaam

**Comment by Baaaaam** [comment]
If lost my wifi connection :(

If you have permission on the cyclus docker hub you can do it yourself:
>docker pull cyclus/cycamore:latest
>cd cymetric/docker/cymetric-deps
>docker build -t cyclus/cymetric-deps:latest .
>docker tag cyclus/cymetric-deps:latest cyclus/cymetric-deps:latest
>docker push cyclus/cymetric-deps

**Comment by scopatz** [comment]
Yeah, I do. I think I started the dockerhub group even :)

**Comment by Baaaaam** [comment]
Nice sorry for the inconvenience... ;)

**Comment by scopatz** [comment]
Oh no problem, thanks so much for helping debug this.

**Comment by scopatz** [comment]
And  woohoo! It builds!

**Comment by Baaaaam** [comment]
Great!!!!

**Comment by Baaaaam** [comment]
Back on my ubuntu issue...
my configuration:
Ubuntu 16.04
Python 2.7
Cyclus Core 1.4.0 (1.4.1-101-gf1b2546)
Dependencies:
   Boost    1_58
   Coin-Cbc 2.8.12
   Coin-Clp 1.15.10
   Hdf5     1.8.16-
   Sqlite3  3.11.0
   xml2     2.9.3
   xml++    2.40.1


`Cyclus` and `Cymetric` installs script run perfectly whitout error.
`Cyclus_unit_test works` well

Cymetric nosetest fails:

> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139819914098432:
>   #000: ../../../src/H5D.c line 358 in H5Dopen2(): not found
>     major: Dataset
>     minor: Object not found
>   #001: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
>     major: Symbol table
>     minor: Object not found
>   #002: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
>     major: Symbol table
>     minor: Object not found
>   #003: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
>     major: Symbol table
>     minor: Callback failed
>   #004: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'AgentEntry' doesn't exist
>     major: Symbol table
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139819914098432:
>   #000: ../../../src/H5D.c line 534 in H5Dget_type(): not a dataset
>     major: Invalid arguments to routine
>     minor: Inappropriate type
> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139819914098432:
>   #000: ../../../src/H5Tfields.c line 87 in H5Tget_nmembers(): not a datatype
>     major: Invalid arguments to routine
>     minor: Inappropriate type
> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139819914098432:
>   #000: ../../../src/H5D.c line 534 in H5Dget_type(): not a dataset
>     major: Invalid arguments to routine
>     minor: Inappropriate type
> HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139819914098432:
>   #000: ../../../src/H5T.c line 2097 in H5Tget_size(): not a datatype
>     major: Invalid arguments to routine
>     minor: Inappropriate type
> E.....E.E[1]    25502 segmentation fault (core dumped)  nosetests -w tests/

and trying to import cymetric in python fails too and ends up on a backtrace:

> Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
> [GCC 5.3.1 20160413] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cymetric as cym
> *** Error in `python': munmap_chunk(): invalid pointer: 0x0000000001c623e0 *** 


[Here](https://gist.github.com/Baaaaam/d86419cd802ad72f3410a200e57344e3) is a gist with the full backtrace.

not sure if the problem comes from me, or Cymetric, let me know if you need me to fix something !

**Comment by scopatz** [comment]
Hi @Baaaaam, gdb backtraces are generally not super helpful when debugging Python.  Could you you try reposting the pdb one please?

**Comment by Baaaaam** [comment]
@scopatz how do I get it ?

**Comment by scopatz** [comment]
It isn't a big deal right no because I think I have solved the problem. But Python comes with its own debugger. So you should normally just need to run python with `python -m pdb`.  For nose, you can drop in on the first error with, `nosetests --pdb`

**Comment by scopatz** [comment]
I think the recent cyclus updates in #1310 should fix this locally too

**Comment by Baaaaam** [comment]
update on this:
[nosetest](https://gist.github.com/Baaaaam/6979eab9fe414b1dea9abc10d8ea3ddd)

[python import cymetric](https://gist.github.com/Baaaaam/22a054a78889ccdf6e9e9c16b2f77c42)

**Comment by scopatz** [comment]
Do you have time to jump on hangouts now?

**Comment by scopatz** [comment]
I think your install is in a bad state

**Comment by Baaaaam** [comment]
I have 1/2 h.
I wait for your call

**Comment by Baaaaam** [comment]
@scopatz I still have the same problem while trying to import cymetric

> python -m pdf test.py
> > /home/mouginot/work/test/test.py(1)<module>()
> -> import cymetric as cym
> (Pdb) c
> [1]    6831 segmentation fault (core dumped)  python -m pdb test.py

test.py contains only:
`import cymetric as cym`

**Comment by scopatz** [comment]
Ok, can you try doing `gdb python` and then in gdb, running `run test.py` and then `bt` please?

**Comment by Baaaaam** [comment]
https://gist.github.com/Baaaaam/73df2a4b61c536a9cb5d147add30be21

**Comment by scopatz** [comment]
This is a PyNE issue, it looks like.  Try uninstalling PyNE and/or reinstalling it

**Comment by Baaaaam** [comment]
You were right ! this is a pyne issue.
after uninstalling PyNE it works.

but I can have PyNE installed and Cymetric working :(

Should I merge this a post a PyNE issue ?

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Robert and I are working though some of the pyne issues.  Your pyne might just be out of date and need reinstalling/.

**Pull request merged**
