### PR TITLE
add units in inventory

### PR DESCRIPTION
**Pull request by bam241**
this should fix error in cyclus/cyclus#1492 which adds units to TimeSeries and inventory tables

### CODE REVIEW

**Comment by gonuke** [comment]
I just merged the Cyclus change - can you relaunch tests with the updated image?

**Comment by gonuke** [comment]
This PR does nothing but whitespace changes...????

**Comment by bam241** [comment]
@gonuke this should be in order now.
(forced cycamore docker update, with an empty PR and put back my changes)
Sorry about that.

**Comment by bam241** [comment]
this is correct.

We don't have test for the root metrics, as they should be natively translated into `Panda Dataframe`.
So it is somehow tested through the test_root_metrics.py, but the translator can translate any table shape into a `PDF`. Shape is not hard coded...

**Comment by gonuke** [comment]
Thanks @bam241 - will you update the cymetric image used for upstream testing?

**Comment by bam241** [comment]
this should be done automatically

**Pull request merged**
