### PR TITLE
fixing nosetest 

### PR DESCRIPTION
**Pull request by bam241**
@scopatz
 this is one supposed to work (I reactivated the CI run before merging...)

### CODE REVIEW

**Comment by bam241** [comment]
Shall we add PyNE to cymetric-dependencies ?

**Comment by scopatz** [comment]
Yes, probably. We should add pyne as dep.

**Comment by scopatz** [comment]
Is this ready to go?

**Comment by bam241** [comment]
@scopatz yes thank you

**Comment by scopatz** [comment]
Thanks @bam241!

**Pull request merged**
