### PR TITLE
Base metrics

### PR DESCRIPTION
**Pull request by opotowsky**
The most verbose version of activity (activity of every nuclide within each composition) is now a metric!

### CODE REVIEW

**Comment by opotowsky** [comment]
Hey @scopatz or @gonuke (since I know you wanted to review a PR):

I'm seeking advice from the wise. My history is really messed up because I must have `git spazzed` a lot the last week or so. I can make this a lot cleaner by putting these changes in a new branch. Let me know what I should do.

**Comment by scopatz** [comment]
I don't see what is wrong with your history.

**Comment by opotowsky** [comment]
If you say so! I know people who would shame me (but I'm not currently protected by a no-judgment zone).

**Comment by scopatz** [comment]
Thanks @opotowsky - Great additions! Activity came up on yesterday's FCO call, again.

**Pull request merged**
