### PR TITLE
Fco elec

### PR DESCRIPTION
**Pull request by opotowsky**
Metric for Electricity Generated (per year). 

I'm not sure this is the best way to do it, but it seemed easy to keep it a pandas series the whole time.

### CODE REVIEW

**Comment by scopatz** [comment]
This doesn't build on my system because of an unrelated cython typesystem bug.  Does this happen to you @opotowsky?

**Comment by opotowsky** [comment]
@scopatz I just double checked and it build fine for me!

**Comment by scopatz** [comment]
from a clean build?  No cython errors in the middle?

**Comment by scopatz** [comment]
Also, what version of cyclus are you on?

**Comment by opotowsky** [comment]
Currently, I only get NumPy issues:
```
Scanning dependencies of target ReplicatePythonSourceTree
[ 25%] [ 50%] Compiling Cython CXX source for cyclus...
Compiling Cython CXX source for typesystem...
[ 50%] Built target ReplicatePythonSourceTree
Scanning dependencies of target cyclus
[ 75%] Building CXX object cymetric/CMakeFiles/cyclus.dir/cyclus.cxx.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/opotowsky/cyclus/cymetric/build/cymetric/cyclus.cxx:252:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
Scanning dependencies of target typesystem
[100%] Building CXX object cymetric/CMakeFiles/typesystem.dir/typesystem.cxx.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/opotowsky/cyclus/cymetric/build/cymetric/typesystem.cxx:253:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
```

I developed this on the most recent changes using the develop branch but am currently on cyclus 1.2. I'll update cyclus and re-check this.

**Comment by scopatz** [comment]
Fix available in #58

**Comment by scopatz** [comment]
This seems to have a merge conflict now @opotowsky.  Please update.

**Comment by opotowsky** [comment]
Now my test fails even though I refactored the entire metric in a (better?) way:

```
======================================================================
ERROR: __main__.test_fco_electricity_gen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "tests/test_metrics.py", line 247, in test_fco_electricity_gen
    obs = metrics.fco_electricity_gen.func(series)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/metrics.py", line 286, in fco_electricity_gen
    elec = series[0].reset_index()
AttributeError: 'numpy.float64' object has no attribute 'reset_index'

----------------------------------------------------------------------
Ran 7 tests in 0.216s

FAILED (errors=1)
```

**Comment by scopatz** [comment]
`series[0]` is clearly a float.  It is probably grabbing the first row from a data frame or Series or something.  More refactoring is needed. Try printing out the value of the `series` variable.

**Comment by opotowsky** [comment]
Fixed it! Bad value and some syntax. How silly. Thanks for looking at it @scopatz. Ready for merging when you are.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
