### PR TITLE
Add Dockerhub Authentication

### PR DESCRIPTION
**Pull request by stompsjo**
This PR adds Dockerhub authentication for CI as a result of the changing Dockerhub policy.

### CODE REVIEW

**Comment by katyhuff** [comment]
This seems like this relies on the environment variables DOCKERHUB_USER and DOCKERHUB_PASS to be set behind the scenes in the circle virtual instance environment. I'll reveal my ignorance of the current dockerhub strategy by asking... is that currently the case through the cymetric github webhook, and if not, is there documentation describing how this authentication data is set in the environment upstream?

**Comment by stompsjo** [comment]
I will ping @bam241 to answer that question fully, but I believe the proper authentication is stored via a "cyclus" bot account on Dockerhub, or should be...?

**Comment by katyhuff** [comment]
That would make sense.

**Comment by bam241** [comment]
Yes, 

but for cyclus this is a multiple layer problem, we need :
- a low security level for log/pass to docker-hub bot to allow CI to get an identity to pull the cyclus/cyclus docker image (have an identity allow more pull from dockerhub)
- a higher security level, that will allow to push the new image to dockerhub, to trigger other CI build (cycamore and cymetric) to build new Debian package and push them

we already have the second one, but when setting the first, one reduce the security of what already exists as we need to pass those log/pass to fork when they do a PR, so we don't control to which fork we forward those information.
There is a way in CI, to limit which users can access which context, so we can allow only the `cyclus` user on GitHub to access the "high" security level, (as the push jobs are only done on merge to `main/master` they are accomplished by cyclus.)
... but I think one need to make sure that the other forks won't get access to them... test that I did not get the time to do...

Let me know if any of this does not make sense, it might be a good conversation for the next Cyclus Dev Call :)

**Comment by katyhuff** [comment]
Gotcha. Interesting. Makes sense. Thanks for the explanation!

**Comment by gonuke** [comment]
I think you can withdraw this PR as we move to github actions.  We aren't there yet with Cymetric, but we won't invest more in the current build infrastruture

**Comment by stompsjo** [comment]
Can do! Closing this PR.

**Pull request closed without merging**
