### PR TITLE
Decommseries

### PR DESCRIPTION
**Pull request by opotowsky**
Built on https://github.com/cyclus/cymetric/pull/92

This simply makes a time series of agent decommission from the agent exit table

### CODE REVIEW

**Comment by opotowsky** [comment]
anyone care to have a look? @rwcarlsen @Baaaaam @rwcarlsen @gonuke @scopatz

**Comment by rwcarlsen** [comment]
Other than the rebase after #92 is merged, LGTM.

**Comment by scopatz** [comment]
Looking now.

**Comment by scopatz** [comment]
Yep, looks good to me.

**Comment by opotowsky** [comment]
rebased, @rwcarlsen, and thanks for the look, @scopatz!

**Comment by scopatz** [comment]
np! Thanks for putting this in!

**Comment by rwcarlsen** [comment]
Now that #92 is in, you need to:

```bash
git checkout develop
git fetch upstream
git merge upstream/develop
git checkout decommseries
git rebase --onto develop 9776f51 decommseries
```

**Comment by opotowsky** [comment]
@rwcarlsen ready when CI finishes!

**Pull request merged**
