### PR TITLE
Fixtests

### PR DESCRIPTION
**Pull request by opotowsky**
This should fix https://github.com/cyclus/cymetric/issues/74. 

Please check my work here (https://github.com/opotowsky/cymetric/commit/00252cb71c90532af8e4baec554d7f00930b2ab2#diff-ed85166e54c2abaa1e8a2fcc867ad749R32) carefully; I'm not sure if I implemented this correctly

### CODE REVIEW

**Comment by gidden** [comment]
hi @opotowsky, would you mind cherry-picking the two relevant commits here? thanks!

**Comment by opotowsky** [comment]
I think I did this correctly. Thanks for promoting history beautification, @gidden!

**Comment by gidden** [comment]
Looks good to me, waiting for CI

**Comment by opotowsky** [comment]
Aw, this is going to have to be dependent on the dbtypes PRs

**Comment by gidden** [comment]
Yeah it will fail until we find a solution

**Comment by opotowsky** [comment]
Ahhhh, genapi.py in cymetric is still configured to look for columns that aren't there any longer.

**Comment by opotowsky** [comment]
crap, I screwed up the history when trying to rebase....

**Comment by gidden** [comment]
looks good, thanks @opotowsky

**Comment by gidden** [comment]
@rwcarlsen, any idea why [this error](https://circleci.com/gh/cyclus/cymetric/14?utm_campaign=build-failed&utm_medium=email&utm_source=notification) might have occurred?

**Pull request merged**
